# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://SimonCW.github.io/roster2ical/"

git_url = "https://github.com/SimonCW/roster2ical/tree/{branch}/"

def custom_doc_links(name): return None
